/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'FreqMsg'
 * message type.
 */

public class FreqMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 144;

    /** Create a new FreqMsg of size 4. */
    public FreqMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new FreqMsg of the given data_length. */
    public FreqMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FreqMsg with the given data_length
     * and base offset.
     */
    public FreqMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FreqMsg using the given byte array
     * as backing store.
     */
    public FreqMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FreqMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public FreqMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FreqMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public FreqMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FreqMsg embedded in the given message
     * at the given base offset.
     */
    public FreqMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FreqMsg embedded in the given message
     * at the given base offset and length.
     */
    public FreqMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <FreqMsg> \n";
      try {
        s += "  [head=0x"+Long.toHexString(get_head())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [frequency=0x"+Long.toHexString(get_frequency())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: head
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'head' is signed (false).
     */
    public static boolean isSigned_head() {
        return false;
    }

    /**
     * Return whether the field 'head' is an array (false).
     */
    public static boolean isArray_head() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'head'
     */
    public static int offset_head() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'head'
     */
    public static int offsetBits_head() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'head'
     */
    public int get_head() {
        return (int)getUIntBEElement(offsetBits_head(), 16);
    }

    /**
     * Set the value of the field 'head'
     */
    public void set_head(int value) {
        setUIntBEElement(offsetBits_head(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'head'
     */
    public static int size_head() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'head'
     */
    public static int sizeBits_head() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: frequency
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'frequency' is signed (false).
     */
    public static boolean isSigned_frequency() {
        return false;
    }

    /**
     * Return whether the field 'frequency' is an array (false).
     */
    public static boolean isArray_frequency() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'frequency'
     */
    public static int offset_frequency() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'frequency'
     */
    public static int offsetBits_frequency() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'frequency'
     */
    public int get_frequency() {
        return (int)getUIntBEElement(offsetBits_frequency(), 16);
    }

    /**
     * Set the value of the field 'frequency'
     */
    public void set_frequency(int value) {
        setUIntBEElement(offsetBits_frequency(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'frequency'
     */
    public static int size_frequency() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'frequency'
     */
    public static int sizeBits_frequency() {
        return 16;
    }

}
